### PR TITLE
Fix redundant semicolon in page

### LINKED ISSUE #95: [bug] Redundant semicolon in page
After deploying `v0.5.0`, it is found that there is a redundant semicolon at the end of the page.

### PR DESCRIPTION
**Pull request by htbkoo**
fixes #95

### CODE REVIEW

File: src/services/MuiThemeFactory.tsx [hunk 1]
```diff
@@ -57,7 +57,7 @@ export const AppThemeProvider = ({ children }: { children?: React.ReactNode }) =
 
     return (
         <DarkLightModeContext.Provider value={{ darkLightMode, setDarkLightMode }}>
-            <MuiThemeProvider theme={theme}>{children}</MuiThemeProvider>;
+            <MuiThemeProvider theme={theme}>{children}</MuiThemeProvider>
```
Comment (htbkoo) [inline src/services/MuiThemeFactory.tsx:60]: The culprit is this commit: https://github.com/htbkoo/personal-portfolio/commit/97be0ccfd7b2f27a4a29226073b26413f846c715#diff-5a60df4d813739d14912a4819fe2e3da94e0ce4606ad54b15fda23523fe1de4bR50

**Comment by htbkoo** [comment]
Wonder if there is any linting rules / tools to prevent something like this in the future......
